# Header

menu:
  ğŸ¡æˆ‘çš„ä¸»é¡µ: /
  ğŸ“•éšç¬”è®°äº‹: /tags/notes/
  ğŸ“·äººé—´ç¾å¥½: /photos/
  ğŸ‘”ä¸ªäººç®€å†:
  ğŸ“ç•™è¨€ç°¿: /Guestbook/

# SubNav
subnav:
  rss: "#"
  mail: "mailto:itboy001@qq.com"
  qq: "#"
  weixin: "#"
  #github: "#"
  #weibo: "#"
  #zhihu: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: more
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: false
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'Thank you for your support and encouragement'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: 
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: 

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#ä½ çš„å¤´åƒurl
avatar:

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

#6ã€Valine https://valine.js.org
valine:
  appId: "" #Leancloudåº”ç”¨çš„appId
  appKey: "" #Leancloudåº”ç”¨çš„appKey
  verify: false #éªŒè¯ç 
  notify: true #è¯„è®ºå›å¤æé†’
  avatar: robohash #è¯„è®ºåˆ—è¡¨å¤´åƒæ ·å¼ï¼š''/mm/identicon/monsterid/wavatar/retro/hide
  #avatar_cdn: "" #å¤´åƒCDN
  placeholder: 
    "å‹æƒ…æç¤ºï¼Œç•™ä¸‹æ­£ç¡®çš„é‚®ç®±åœ°å€å¯ä»¥ç¬¬ä¸€æ—¶é—´è·å–è¯„è®ºåé¦ˆã€‚" #è¯„è®ºæ¡†å ä½ç¬¦
  pageSize: 12 #è¯„è®ºåˆ†é¡µ
  visitor: true #é˜…è¯»ç»Ÿè®¡
  recordIP: true #è®°å½•IP
  enableQQ: true #QQå¤´åƒ
  #serverURLs: ""
  version: latest #ä¾‹å¦‚ latest 1.4.5
#  emojiCDN: https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/
#  emojiMaps:
#    smile: e3/2018new_weixioa02_org.png
#    lovely: 09/2018new_keai_org.png


# ç‰ˆæƒå£°æ˜
#åœ¨éœ€è¦è¿›è¡Œç‰ˆæƒå£°æ˜çš„æ–‡ç« çš„mdæ–‡ä»¶å¤´éƒ¨ï¼Œè®¾ç½®å±æ€§declare: trueã€‚
#ç‰ˆæƒåŸºç¡€è®¾å®šï¼š0-å…³é—­å£°æ˜ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰declare: trueå±æ€§ï¼Œæ‰æœ‰ç‰ˆæƒå£°æ˜ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰ç‰ˆæƒå£°æ˜
declare:
  declare_type: 1
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #å½“å‰åº”ç”¨çš„ç‰ˆæƒåè®®åœ°å€ã€‚
  licensee_name: 'CC BY-NC-SA 4.0'                                        #ç‰ˆæƒåè®®çš„åç§°
  licensee_alias: 'çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™…è®¸å¯åè®®'       # aliasåˆ«å
  licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png    #ç‰ˆæƒåè®®çš„Logo


# å¿ƒçŸ¥å¤©æ°”(å¦‚æœä¸ç”¨ä¸ºfalse):https://www.seniverse.com
xinzhi_weather: true

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#ccc,#000)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# Security
## æ–‡ç« åŠ å¯† hexo-blog-encrypt
encrypt:
    enable: true

#å­—æ•°ã€é˜…è¯»æ—¶é•¿ç»Ÿè®¡
word_count: true

#ä¸è’œå­è®¿é—®é‡ç»Ÿè®¡
busuanzi:
  enable: true
  site_visit: true  # ç«™ç‚¹è®¿é—®é‡æ˜¾ç¤º
  article_visit: true  # æ–‡ç« è®¿é—®é‡æ˜¾ç¤º

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'


friends:
  å‹æƒ…é“¾æ¥1: http://localhost:4000/
  å‹æƒ…é“¾æ¥2: http://localhost:4000/
  å‹æƒ…é“¾æ¥3: http://localhost:4000/
  å‹æƒ…é“¾æ¥4: http://localhost:4000/
  å‹æƒ…é“¾æ¥5: http://localhost:4000/
  å‹æƒ…é“¾æ¥6: http://localhost:4000/


aboutme: å¤§å¤šæ•°é‡Œæœ€ä¸æ˜¾çœ¼çš„é‚£ä¸€ä¸ª<br><br>å¯¹ç§‘æŠ€ç”Ÿæ´»å……æ»¡å…´è¶£<br><br>å®Œå–„ä¸­...